/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeader2: typeof import('./src/components/AppHeader2.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PoseFeatures: typeof import('./src/components/PoseFeatures.vue')['default']
    PoseSkeleton: typeof import('./src/components/PoseSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
