version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: fitai-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fitai_db
      MYSQL_USER: fitai_user
      MYSQL_PASSWORD: fitai_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 
